#!/usr/bin/env bash

# Copyright 2025 Omar Tiffer
#
# Portions of this file are based on code from ThePrimeagen’s
# "My Dev Setup Is Better Than Yours" course on Frontend Masters.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

switch_to() {
    local sname=$1

    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t "$sname"
    else
        tmux switch-client -t "$sname"
    fi
}

selected_dir=$(find "$HOME"/.local "$HOME"/.config "$HOME"/WORKSPACE "$HOME"/COURSES -maxdepth 1 -mindepth 1 -type d | fzf)

if [[ -z "$selected_dir" ]]; then
    exit 0
fi

session_name=$(basename "$selected_dir" | tr ".,: " "____")

if tmux has-session -t="$session_name" 2>/dev/null; then
    switch_to "$session_name"
else
    tmux new-session -ds "$session_name" -c "$selected_dir"
    switch_to "$session_name"
    tmux send-keys -t "$session_name" "tmux-session-bootstrapper" ^M
fi
