#!/usr/bin/env bash

# Copyright 2025 Omar Tiffer
#
# This file is based on code from ThePrimeagen’s
# "My Dev Setup Is Better Than Yours" course on Frontend Masters.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ -x ./.tmxsrc ]]; then
    source ./.tmxsrc
elif [[ -x ~/.tmxsrc ]]; then
    source ~/.config/tmux/.tmxsrc
fi
clear
